Sample/Models/Prodact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sample.Models
{
    public class Prodact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set;}
        public string Supplier { get; set; }

    }
}

Sample/Controllers/HomeController.cs
using Sample.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sample.Controllers
{
    public class HomeController : Controller
    { 
         
        public ActionResult Index()
        {
            ViewBag.FirstName = "Narendra";
            ViewBag.SecondName = "Dusari";
            ViewBag.Address = "near water plant veerammacolony,konadmodu";

            return View();
        }

        public ActionResult Login()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        
       
    }
}

Sample/Controllers/ProdactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sample.Config;
using Sample.Models;

namespace Sample.Controllers
{
    public class ProdactController : Controller
    {
        // GET: Prodact
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveProduct(Prodact prodact)
        {
            using (SqlConnection con = new SqlConnection(DataBase.GetConnection()))
            {
                using (SqlCommand cmd = new SqlCommand("insert into Prodacts(Name,Price,Supplier) values('" + prodact.Name + "','" + prodact.Price + "','" + prodact.Supplier + "')" ,con))
                {

                    if (con.State != System.Data.ConnectionState.Open)
                            con.Open();
                

                cmd.ExecuteNonQuery();

                }
            }
           return Content("Result is saved in database:");
        }
        public ActionResult viewall()
        {
            List<Prodact> prodact = new List<Prodact>();
            using (SqlConnection connect = new SqlConnection(DataBase.GetConnection()))
            {
                using (SqlCommand cmd = new SqlCommand("select * from Prodacts", connect))
                {
                    if (connect.State != System.Data.ConnectionState.Open)
                        connect.Open();
                    SqlDataReader sdr = cmd.ExecuteReader();
                    DataTable dtProdacts = new DataTable();
                    dtProdacts.Load(sdr);
                    foreach (DataRow row in dtProdacts.Rows)
                    {
                        prodact.Add(
                            new Prodact
                            {
                                Id = Convert.ToInt32(row["id"]),
                                Name = row["Name"].ToString(),
                                Price = Convert.ToDecimal(row["Price"]),
                                Supplier = row["Supplier"].ToString()
                            }
                            );
                    }
                }

            }
                return View(prodact);
        }
         
    }
}

Sample/Views/Home/Admin.cshtml
@{
    ViewBag.Title = "Admin";
}

<h2>Admin</h2>

Sample/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Welcome Admin</h1>
    <p class="lead">This is a ONLINE EXAMINATION SYSTEM .</p>
    <p>
        <a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a>
    </p>
</div>



<h3>AUTHOR</h3>
<p> First Name : @ViewBag.FirstName</p>
<p> Second Name : @ViewBag.SecondName</p>
<p> Address : @ViewBag.Address</p>

Sample/Views/Home/Invigilator.cshtml
@{
    ViewBag.Title = "Invigilator";
}

<h2>Invigilator</h2>

Sample/Views/Home/Login.cshtml
@{
    ViewBag.Title = "LOGIN";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<!DOCTYPE HTML>
<html>
<head>
    <title>Square login form Responsive Widget  Website Template | Home:: w3layouts</title>
    <link href="~/Content/style.css" rel="stylesheet" type="text/css" media="all" />
   
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   
</head>
<body>
    <!--header start here-->
    <div class="login-form">
        <div class="top-login">
            <span><img src="~/images/group.png" alt="" /></span>
        </div>
        <h1>Login</h1>
        <div class="login-top">
            <form>
                <div class="login-ic">
                    <i></i>
                    <input type="text" value="User name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'User name';}" />
                    <div class="clear"> </div>
                </div>
                <div class="login-ic">
                    <i class="icon"></i>
                    <input type="password" value="Password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'password';}" />
                    <div class="clear"> </div>
                </div>

                <div class="log-bwn">
                    <input type="submit" value="Login">
                </div>
            </form>
        </div>
        <p class="login-top"><a>@DateTime.Now.Year</a></p>
    </div>
</body>
</html>

Sample/Views/Home/Student.cshtml
@{
    ViewBag.Title = "Student";
}

<h2>Student</h2>

Sample/Views/Prodact/Create.cshtml
@model Sample.Models.Prodact

@{
    ViewBag.Title = "Create";
}

<h2>Product Information</h2>

@using (Html.BeginForm("SaveProduct","Prodact" )) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Supplier, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Supplier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="SaveProduct" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

Sample/Views/Prodact/viewall.cshtml
@model IEnumerable<Sample.Models.Prodact>

@{
    ViewBag.Title = "viewall";
}

<h2>viewall</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Supplier)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Supplier)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Sample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ONLINE EXAM SYSTEM</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Login", "Login", "Home")</li>
                    <li>@Html.ActionLink("ProductTable", "viewall", "Prodact")</li>
                    <li>@Html.ActionLink("ProductDetailsReg", "Create", "Prodact")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Online Exam Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

   
</body>
</html>